project_path: '/home/onyxia/work/deduplication/'

id_col: 'id'
title_col: 'title'
description_col: 'description'
company_col: 'company_name'
location_col: 'location'
country_col: 'country_id'
date_col: 'retrieval_date'

language_col: 'language'
filtered_description_col: 'filtered_description'

concatenated_col_names:
    normal: 'concatenated_offer'
    filtered: 'concatenated_filtered_offer'

beginning_prefix: 'beginning_'
end_prefix: 'end_'

normal_description_type: 'normal'
filtered_description_type: 'filtered'

batch_size: 8
chunk_size: 5000

threshold_similarity:
  monolingual:
    title: 0.8
    description: 0.8
    company_name: 0.8
    location: 0.8
  multilingual:
    title: 0.6
    description: 0.1
    company_name: 0.8
    location: 0.8

threshold_partial:
  monolingual: 0.05
  multilingual: 0.10

dim_tokens: 100
