project_path: '/home/onyxia/work/deduplication/'

concatenated_col_name: 'text'
lemmatized_col_name: 'lemmatized_text'

id_col: 'id'
description_col: 'description'
date_col: 'retrieval_date'

batch_size: 128
chunk_size: 10000
