project_path: '/home/onyxia/work/deduplication/'

id_col: 'id'
title_col: 'title'
description_col: 'description'
company_col: 'company_name'
location_col: 'location'
country_col: 'country_id'
date_col: 'retrieval_date'

str_cols:
    ['title', 'company_name', 'location', 'description']

language_col: 'language'
filtered_description_col: 'filtered_description'

concatenated_col_names:
    normal: 'concatenated_offer'
    filtered: 'concatenated_filtered_offer'

beginning_prefix: 'beginning_'
end_prefix: 'end_'

normal_description_type: 'normal'
filtered_description_type: 'filtered'

batch_size: 8
chunk_size: 5000

threshold_similarity:
  date: 100
  monolingual:
    title: 0.8
    company_name: 0.8
    location: 0.8
    True:
      description: 0.8
      filtered_description: 0.85
    False:
      description: 0.75
      filtered_description: 0.8
  multilingual:
    title: 0.5
    company_name: 0.8
    location: 0.8
    True:
      description: 0.25
      filtered_description: 0.3
    False:
      description: 0.1
      filtered_description: 0.15

threshold_partial:
  monolingual: 0.05
  multilingual: 0.10
  too_much_monolingual: 0.50
  too_much_multilingual: 1.00

dim_tokens: 100
