project_path: '/home/onyxia/work/deduplication/'

concatenated_col_name: 'text'
reduced_col_name: 'reduced_text'

id_col: 'id'
description_col: 'description'
date_col: 'retrieval_date'

batch_size: 64
chunk_size: 5000

threshold_partial: 0.1
