concatenated_col_name: 'text'

id_col: 'id'
description_col: 'description'
date_col: 'retrieval_date'

languages_list:
    ['danish',
    'dutch',
    'english',
    'finnish',
    'french',
    'german',
    'hungarian',
    'portuguese',
    'romanian',
    'russian',
    'spanish']
