project_path: '/home/onyxia/work/deduplication/'

id_col: 'id'
description_col: 'description'
date_col: 'retrieval_date'

concatenated_col_name: 'concatenated_offer'

beginning_col_prefix: 'beginning_'
end_col_prefix: 'end_'

str_cols:
    ['title', 'company_name', 'location', 'description']


batch_size: 64
chunk_size: 5000

threshold_partial: 0.20
