project_path: '/home/onyxia/work/deduplication/'

id_col: 'id'
title_col: 'title'
description_col: 'description'
company_col: 'company_name'
location_col: 'location'
country_col: 'country_id'
date_col: 'retrieval_date'

language_col: 'language'
filtered_description_col: 'filtered_description'

concatenated_col_names:
    normal: 'concatenated_offer'
    filtered: 'concatenated_filtered_offer'

beginning_prefix: 'beginning_'
end_prefix: 'end_'

normal_description_type: 'normal'
filtered_description_type: 'filtered'

cols_to_be_similar: ['title', 'company_name', 'location']

batch_size: 8
chunk_size: 5000

threshold_similarity:
  title: 0.8
  title_monolingual: 0.8
  company_name: 0.8
  location: 0.8
threshold_similarity_multilingual:
  title: 0.6  # What is optimal?
  title_monolingual: 0.8
  company_name: 0.75
  location: 0.75

# threshold_partial: 0.25  # What is optimal?
# threshold_partial_multilingual: 0.5  # What is optimal?

dim_tokens: 100
