# cols:
#     id: 'id'
#     title: 'title'
#     company: 'company_name'
#     location: 'location'
#     country: 'country_id'
#     date: 'retrieval_date'
#     description: 'description'
#     language: 'language'

# cols_prefix:
#     concatenated: 'concatenated_'
#     beginning: 'beginning_'
#     end: 'end_'
#     filtered: "filtered_"

str_cols:  # What columns can require cleaning?
    normal: ['title', 'company_name', 'location', 'description']
    filtered: ['title', 'company_name', 'location', 'filtered_description']
    no_description: ['title', 'company_name', 'location']

FULL: "FULL"
PARTIAL: "PARTIAL"
SEMANTIC: "SEMANTIC"
SEMANTIC_PARTIAL: "SEMANTIC_PARTIAL"
SEMANTIC_MULTILINGUAL: "SEMANTIC_MULTILINGUAL"

ner:  # Do we want to compute and use NER?
  compute: False
  use: False

hyperparameters:
    batch_size: 8  # For Transformers
    dim_tokens: 100  # For dimension reduction before computing cosine similarities
    chunk_size: 5000  # Cosine similarity matrix too big to compute, needs to be done by chunks

threshold_date:  # How do we define if the offers are close in time or not?
    far_dates: 100  # Nb of days before offers are considered far apart
    too_much: 500  # Nb of days before we consider the offers cannot be duplicates

thresholds_similarity:  # Minimum requirement of Jaro-Winkler similarity between fields to be considered duplicates
  monolingual:
    close_dates:
      title: 0.8
      company_name: 0.85
      location: 0.85
      description: 0.8
      filtered_description: 0.8
    far_dates:
      title: 0.85
      company_name: 0.9
      location: 0.9
      description: 0.85
      filtered_description: 0.85
  multilingual:
    close_dates:
      title: 0.25
      company_name: 0.8
      location: 0.8
      description: 0.1
      filtered_description: 0.1
    far_dates:
      title: 0.5
      company_name: 0.85
      location: 0.85
      description: 0.25
      filtered_description: 0.25

thresholds_desc_len:  # Thresholds for comparing the differences in length of the descriptions
    absolute:  # Absolute difference in length, in nb of characters
        monolingual:
            PARTIAL: 50  # Above, can be eligible to be a partial duplicate
            NON: 500  # Above, the difference is too big to be eligible to be duplicate at all
        multilingual:
            PARTIAL: 100  # Above, can be eligible to be a partial duplicate
            NON: 1000  # Above, the difference is too big to be eligible to be duplicate at all
    relative:  # Relative difference in length, as a % of characters compared to the shortest one
        monolingual:
            PARTIAL: 0.05  # Above, can be eligible to be a partial duplicate
            NON: 0.25  # Above, the difference is too big to be eligible to be duplicate at all
        multilingual:
            PARTIAL: 0.15  # Above, can be eligible to be a partial duplicate
            NON: 0.50  # Above, the difference is too big to be eligible to be duplicate at all
