project_path: '/home/onyxia/work/deduplication/'

id_col: 'id'
title_col: 'title'
description_col: 'description'
language_col: 'country_id'
date_col: 'retrieval_date'

concatenated_col_name: 'concatenated_offer'

beginning_prefix: 'beginning_'
end_prefix: 'end_'

batch_size: 64
chunk_size: 5000

threshold_titles: 0.8
threshold_titles_multilingual: 0.4
threshold_partial: 0.20
