# cols:
#     id: 'id'
#     title: 'title'
#     company: 'company_name'
#     location: 'location'
#     country: 'country_id'
#     date: 'retrieval_date'
#     description: 'description'
#     language: 'language'

# cols_prefix:
#     concatenated: 'concatenated_'
#     beginning: 'beginning_'
#     end: 'end_'

FULL: "FULL"
PARTIAL: "PARTIAL"
SEMANTIC: "SEMANTIC"
SEMANTIC_MULTILINGUAL: "SEMANTIC_MULTILINGUAL"

str_cols:
    normal: ['title', 'company_name', 'location', 'description']
    filtered: ['title', 'company_name', 'location', 'filtered_description']
    no_description: ['title', 'company_name', 'location']

hyperparameters:
    batch_size: 8
    dim_tokens: 100
    chunk_size: 5000

thresholds_similarity:
  monolingual:
    close_dates:
      title: 0.8
      company_name: 0.8
      location: 0.8
      description: 0.75
      filtered_description: 0.75
    far_dates:
      title: 0.8
      company_name: 0.8
      location: 0.8
      description: 0.8
      filtered_description: 0.8
  multilingual:
    close_dates:
      title: 0.25
      company_name: 0.8
      location: 0.8
      description: 0.1
      filtered_description: 0.1
    far_dates:
      title: 0.5
      company_name: 0.8
      location: 0.8
      description: 0.25
      filtered_description: 0.25

threshold_date: 100

thresholds_desc_len:
    absolute:
        monolingual:
            PARTIAL: 100
            NON: 500
        multilingual:
            PARTIAL: 200
            NON: 1000
    relative:
        monolingual:
            PARTIAL: 0.05
            NON: 0.25
        multilingual:
            PARTIAL: 0.10
            NON: 0.50
